### ISSUE TITLE
`msgraph` todo's

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#310]
### Description
TODO's left over from implementation of #284 

**getDrive()**
- [ ] pass a string drive id as the specifier
- [ ] how will we get a list of drives?
- [ ] can we use /me/drive to get the user's default drive?
- [ ] maybe error if no id

**getFolder()**
- [ ] support for `$filter` query (maps to $filter, must be URI encoded)
- [ ] support `select` query `Eg: id,@microsoft.graph.downloadUrl`

**getFile()**
- [ ] support for `$filter` query (maps to $filter, must be URI encoded)
- [ ] support `select` query `Eg: id,@microsoft.graph.downloadUrl`
- [ ] if response is a single file, it needs to be nested in an array

**Comment by mtuchi** [comment]
Related https://github.com/OpenFn/adaptors/issues/500
