### ISSUE TITLE
Implement OpenFn adaptor for OpenLIMS

### ISSUE THREAD

**Issue by christad92** [OpenFn/adaptors#533]
Implement an OpenFn adaptor for OpenLIMS that will enable users to authorize connection via Oauth and perform requisition and fulfillment operations. 

To start, this adaptor should:
- [ ] handle authentication via Oauth
- [ ] include a generic GET helper so we can get any resource
- [ ] include a generic POST so we can create any resource
- [ ] include a generic PUT so we can update any resource

_Later_ we can consider adding more abstraction and specific helper functions. Use cases we want to support...

Requisition ([API](http://build.openlmis.org/view/Services-Build-Monitor/job/OpenLMIS-requisition-pipeline/job/rel-3.1.1/lastSuccessfulBuild/artifact/build/resources/main/api-definition.html#Getting-Started)): 
- [ ] Initiate a requisition
- [ ] Submit a requisition
- [ ] Get all requisitions
- [ ] Fetch a specific requisition via ID
- [ ] Update a requisition 
- [ ] Approve a requisition
- [ ] Convert requisition lists to orders

Fulfilment ([API](http://build.openlmis.org/view/Services-Build-Monitor/job/OpenLMIS-fulfillment-pipeline/job/rel-3.0.1/lastSuccessfulBuild/artifact/build/resources/main/api-definition.html#)):
- [ ] Create a new order 
- [ ] Get all orders 
- [ ] Get order by ID

Demo Server Credentials: 
URL: https://demo-v3.openlmis.org/#!/home
username: **administrator**
password: **password**

OpenLMIS API requests are authenticated by an OAuth2 access token passed as a query parameter. See a sample API request below: 

```
GET /api/reports/templates/requisitions/{id}?access_token=
9a556033-ed13-4dde-9561-158469d15134

URI Parameters
id: required (string)

Query Parameters
access_token: required (string)
OAuth2 access token

```

Link to test OAuth2 token here: https://github.com/OpenLMIS/openlmis-auth/blob/master/src/main/resources/db/demo-data/auth.api_keys.csv

**Comment by aleksa-krolls** [comment]
@christad92 @taylordowns2000 we cannot work on an adaptor unless we have credentials to a demo system. I don't see demo system login details provided for OpenLMIS. Do you have a way to get these?

**Comment by christad92** [comment]
@aleksa-krolls we have access to a demo system with tokens we can use to authenticate API requests.

**Comment by aleksa-krolls** [comment]
@christad92 great! Noted for backlog planning in the coming 2 weeks

**Comment by aleksa-krolls** [comment]
hey @mtuchi after you go through the other issues prioritized in this sprint, pls confirm if you'll have space to also take on this issue... and whether this issue should be broken up into smaller issues. (For example, I think we might create follow-up issues to implement specific helper functions for the Fufilment and Requisition use cases that Ayodele detailed above.) I think you'll have space this week, but let @AishaHassen know on Monday and she can adjust the sprint scheduling accordingly. 

If you have any questions about about this app and the adaptor requirements, then pls sync with Ayodele.

**Comment by mtuchi** [comment]
@aleksa-krolls  I think this issue should be split into 3 small issues

1. Add OAuth support and generic helpers (get, post, put)
2. Requisition ([API](http://build.openlmis.org/view/Services-Build-Monitor/job/OpenLMIS-requisition-pipeline/job/rel-3.1.1/lastSuccessfulBuild/artifact/build/resources/main/api-definition.html#Getting-Started)):
3. Fulfillment ([API](http://build.openlmis.org/view/Services-Build-Monitor/job/OpenLMIS-fulfillment-pipeline/job/rel-3.0.1/lastSuccessfulBuild/artifact/build/resources/main/api-definition.html#)):

**Comment by christad92** [comment]
Yeah, this works for me and thanks for the update.

**Comment by christad92** [comment]
@mtuchi What is the status of the Adaptor?

**Comment by mtuchi** [comment]
@christad92 still under review #675

**Comment by josephjclark** [comment]
Hi @aleksa-krolls @christad92 

The basic generic adaptor is nearly ready, but I have a question about auth

Right now the adpator either accepts an oauth token or a "user based" token (username & password). OpenLMIS also supports API keys which allows auth with a code, rather than user/password pair.

Are we happy to just support user tokens or do we want to add API token support too? Do we know what NH will need?

**Comment by aleksa-krolls** [comment]
@josephjclark we don't know what NH needs... and I suspect it will be months before we learn about nigeria-specific requirements, so I'd vote to cut a release for what we have now, and then add an issue to backlog for apiKey support

**Comment by josephjclark** [comment]
That's great, just wanted to check it. No need for an issue at this stage. Thanks!
